version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${HTTP_EXTERNAL_PORT}:80
    volumes:
      - ./:/var/www/test_task:cached
    networks:
      - test_task_external
    restart: always
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        LINUX_USER_ID: ${LINUX_USER_ID}
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/test_task:cached
    depends_on:
      - nginx
      - test-task-database-postgres
    networks:
      - test_task_external
    restart: always

  test-task-database-postgres:
    image: postgres:15.1
    ports:
      - ${DB_POSTGRES_EXTERNAL_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - test_task_external
    volumes:
      - pgdata_15_1:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata_15_1:

networks:
  test_task_external:
    driver: bridge
    name: test_task_external
