Author:
  type: object
  config:
    fields:
      id:
        type: "Int!"
      fullName:
        type: "String!"
      quantityBooks:
        type: "Int!"
      createdAt:
        type: "DateTimeImmutable!"
